apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-version-exporter
  namespace: {{ .Values.serviceMonitorNamespace }}
  labels:
    app: version-exporter
    galleon: {{ .Values.galleonName }}
    {{- range $key, $val := .Values.serviceMonitorLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: version-exporter
      galleon: {{ .Values.galleonName }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.scrapeInterval }}
