{
 "title": "Galleon Fleet Overview",
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(cluster_addon_status, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Kubernetes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"kubernetes\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "EKS-A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"eksa\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Kubevirt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"kubevirt\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Rook-Ceph",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"rook_ceph\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "GPU Operator",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"gpu_operator\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CDI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"cdi\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "ArgoCD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"argocd\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Velero",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_addon_status{cluster=\"$cluster\", component=\"velero\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cluster_addon_status{cluster=\"$cluster\"} == 1) / count(cluster_addon_status{cluster=\"$cluster\"} >= 0) * 100",
     "legendFormat": "Health"
    }
   ]
  }
 ]
}